# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#2) Print:#ask: Use the print function to display the phrase "Hello, Python!".

print("Hello , python!")

#3) Basic data types - CRUD operations:Task: Create variables of each basic data type (integer, float, boolean, string), print their types using type(), update their values, and then delete them.

num = 10
num1 = 5.30
boll = True
strr = "rasheed"
# Print their types using type()
print(type(num))
print(type(num1))
print(type(boll))
print(type(strr))


# Update their values
num = 15
num2 = 7.30
boll = False
strr = "mohammad"

# Print updated variables
print(num)
print(num2)
print(boll)
print(strr)
# Delete them
del num
del num2
del boll
del strr


#4) Math operations: Task: Write a script that asks the user for two numbers, then calculates and prints the sum, difference, product, quotient, and remainder of the first number by the second number.

math = float(input("inter first number : "))
math2 = float(input("enter second number : "))

# Calculate and print the sum, difference, product, quotient, and remainder
print((math + math2))
print({math - math2})
print({math * math2})
print({math / math2})
print({math % math2})


#5) Logic operations:Task: Write a script that asks the user for two boolean values (input as true/false strings), then prints the results of the logical AND, logical OR, and logical NOT operations on the entered values.

# Task 5
# Ask the user for two boolean values

boll1 = input("Enter first boolean (true/false):")
boll2 = input("Enter second boolean (true/false):")

# Print the results of the logical AND, logical OR, and logical NOT operations
print(boll1 and boll2)
print(boll1 or boll2)
print(not boll1)
print(not boll2)


#6) Input:Task: Write a program that asks the user for their name and age, and then prints out a message addressed to them that tells them how many years they have until they turn 100.

# Task 6
# Ask the user for their name and age

name = input("enter your name : ")
age = input("enter your age : ")

# Print out a message addressed to them
print(f"Hello, {name}. You will turn 100 in {100 - age} years.")


#7) print(f" {}"):Task: Write a script that asks the user for their name and favorite food. Then, use an f-string to print a message saying "{name} likes {favorite_food}".

# Task 7
# Ask the user for their name and favorite food
name = input("Enter your name: ")
favorite_food = input("Enter your favorite food: ")

# Print a message
print(f"{name} likes {favorite_food}")

